---
version: "3"

tasks:

  format:
    cmds:
      - fd '.nix' | xargs nixfmt

  switch:
    cmds:
      - sudo nixos-rebuild switch --flake .#x1

  build:
    cmds:
      - sudo nixos-rebuild build --flake .#x1
